42ity/fty-info

src/fty-info.service.in

Problem: access for DB missing

---

README.md

Problem: readme doesn't describe the protocol

---

README.md
include/fty_info.h
src/fty-info.service.in
src/fty_info_server.cc

solution : add vendor, serial, model
Problem: tests could be improved
Solution: improve it

Problem: other infos are missing

---

src/fty_info_server.cc

Problem: Message is not destroyed if it is not fty message

---

src/fty_info_server.cc

Solution : slip the code in different sub-functions
Problem : the sub-type "rack controller" is wrong
Solution : use "rackcontroller" subtype

Problem : fty_info_server is too long

---

src/fty_info.cc
src/fty_info_server.cc

Problem : need to publish announcement to STREAM

---

include/fty_info.h
src/fty_info_server.cc

Problem: There are missing fields in fty info

---

src/fty_info.cc
src/fty_info_server.cc

Solution: Add zloop and polish publish function

Problem: Information is not published regularly

---

Makefile.am
project.xml
src/Makemodule.am
src/fty_info_classes.h
src/fty_info_selftest.cc

Problem: Need class for topology resolving

---

src/topologyresolver.cc
src/topologyresolver.h

Problem: Class file is missing

---

src/fty_info_server.cc
src/topologyresolver.cc

Solution: Do it.
Signed-off-by: Jana Rapava <janarapava@eaton.com>

Problem: We want to use class topologyresolver to get location topology.

---

src/topologyresolver.cc

Solution: Save messages into hash

 Problem: Class is not storing necessary information 

---

src/topologyresolver.cc

Problem: Topology list function is doing nothing

---

src/topologyresolver.cc

Solution: Check the message by IP whether is me

Problem: Reselver is not discovering itself

---

project.xml
src/fty_info_private_selftest.cc
src/topologyresolver.cc
src/topologyresolver.h

Solution: Move it to class structure, create empty test

Problem: Topology string is not owned by class

---

src/topologyresolver.cc

Solution: Write test, fix crash

Problem: No test

---

src/topologyresolver.cc

Solution: Fix memory handling, extend test

Problem: Doublefree

---

src/topologyresolver.cc

Solution: fix it
Signed-off-by: Tomas Halman <Tomas@Halman.net>

Problem: Topology conversion to string is not working

---

Makefile.am
project.xml
src/Makemodule.am
src/fty_info_classes.h
src/fty_info_selftest.cc
src/fty_info_server.cc
src/ftyinfo.cc
src/ftyinfo.h

Solution: extract fty_info_t class into separate file

Problem: zproject regeneration breaks compitation

---

src/ftyinfo.cc
src/topologyresolver.cc
src/topologyresolver.h

Solution: Rewrite clean cache, fix topology string handling

Problem: Memory leak in topology resolver

---

src/fty_info_server.cc

Add INFO in protocol description

---

include/fty_info.h
src/ftyinfo.cc
src/ftyinfo.h

Solution: Propagate it in INFO message.
Signed-off-by: Jana Rapava <janarapava@eaton.com>

Problem: Part number is now available.

---

src/fty_info.cc
src/fty_info_server.cc
src/topologyresolver.cc
src/topologyresolver.h

Problem: We need to publish information on stream when and only when create or update occurs
Signed-off-by: barraudl <lilianbarraud@eaton.com>

Problem: We need to publish information on stream when and only when create or update occurs

---

src/fty_info_server.cc
src/ftyinfo.cc
src/topologyresolver.cc
src/topologyresolver.h

Solution: don't send NA values, check how many values are actually sent

Problem: some information aren't avaible and NA values are confusing

---

src/linuxmetric.cc

Solution: Round them
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>

Problem: Network bandwidth info are not rounded

---

src/fty_info_rc0_runonce.cc
src/ftyinfo.cc

Signed-off-by: Michal Marek <MichalMarek1@eaton.com>

Plug memory leaks in the IP address detection code

---

src/fty_info_rc0_runonce.cc
src/fty_info_server.cc

Solution: replaced newlines with spaces
+ minor fixes

Problem: webUI/DB are not ready for newlines in description

---

src/topologyresolver.cc

Solution: Added zuuid to ASSET_DETAIL message

Problem: missing zuuid in ASSET_DETAIL message

---

src/topologyresolver.cc

Solution: fixed memleak from uuid in MB

Problem: memory leaks due to uuid object not being properly destroyed

---

README.md
src/fty_info.cc
src/fty_info_server.cc
src/selftest-ro/data/hw_cap/42ity-capabilities.dsc
src/selftest-ro/data/ipc-capabilities.dsc
src/selftest-ro/data/ova-capabilities.dsc

Problem: we need new MB request to provide hw capability data

---

src/fty_info_server.cc
src/selftest-ro/data/hw_cap/42ity-capabilities.dsc

This will allow the UI to use different behavior depending on whether we
are running on the rack controller or virtualized.

Add hardware type capability

---

src/ftyinfo.cc

 Problem: OVA status shows serial number as Unknown instead of N/A. 

---

src/fty_info_rc0_runonce.cc

Solution: fixed
Signed-off-by: Barbora Stepankova <BarboraStepankova@eaton.com>

Problem: ext attributes of RC-0 should be RO

---

src/fty_info_server.cc

We end up on with a storm of back-and-forth error messages with fty-sensor-gpio otherwise.

Don't reply to error messages

---

src/fty_info_rc0_runonce.cc

Signed-off-by: barraudl <lilianbarraud@eaton.com>

Fix "readonly for all ext value of rackcontroller-0"

---

src/ftyinfo.cc

sysinfo typo: retrievEing: fixed (1.5.0)

---

src/ftyinfo.cc

Similar to https://github.com/42ity/fty-rest/pull/589

sysinfo typo: retrievEing: fixed

---

src/topologyresolver.cc

Fix memory leak in test

---

include/fty_info.h
src/.valgrind.supp
src/ftyinfo.cc
src/ftyinfo.h

Signed-off-by: Arnaud Quette <ArnaudQuette@eaton.com>

OEM Signature: add licensing portal URL in INFO payload
